=== sourcemeta/one/collections/self/schemas/configuration/configuration.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "The Sourcemeta One configuration file format",
  "description": "The configuration file format used to configured One instances",
  "examples": [
    {
      "url": "https://schemas.example.com"
    }
  ],
  "type": "object",
  "required": [ "url" ],
  "properties": {
    "extends": {
      "$ref": "./extends.json"
    },
    "contents": {
      "$ref": "./contents.json"
    },
    "html": {
      "type": [ "object", "boolean" ],
      "properties": {
        "description": {
          "type": "string"
        },
        "action": {
          "type": "object",
          "required": [ "title", "url", "icon" ],
          "properties": {
            "title": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            },
            "url": {
              "$ref": "../../../../vendor/collections/sourcemeta/std/v0/schemas/2020-12/ietf/uri/url.json"
            }
          },
          "additionalProperties": false
        },
        "head": {
          "type": "string"
        },
        "hero": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "url": {
      "$ref": "../../../../vendor/collections/sourcemeta/std/v0/schemas/2020-12/ietf/uri/url.json"
    }
  },
  "additionalProperties": false
}

=== sourcemeta/one/test/e2e/enterprise/one.json
{
  "url": "http://localhost:8000",
  "html": {
    "hero": "<p class=\"mb-0\">A sample sandbox for testing purposes</p>",
    "action": {
      "title": "Star on GitHub",
      "url": "https://github.com/sourcemeta/one",
      "icon": "github"
    }
  },
  "extends": [ "@self/v1" ],
  "contents": {
    "enterprise": {
      "path": "./schemas/enterprise",
      "lint": {
        "rules": [ "./rules/camelcase.json" ]
      }
    },
    "test": {
      "title": "Test",
      "description": "A directory full of testing schemas",
      "contents": {
        "extension": {
          "baseUri": "https://example.com/extension",
          "path": "./schemas/test/extension"
        },
        "schemas": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/folder",
          "defaultDialect": "http://json-schema.org/draft-07/schema#",
          "resolve": {
            "https://other.com/single.json": "/test/bundling/single.json"
          }
        },
        "camelcase": {
          "contents": {
            "test": {
              "baseUri": "https://sourcemeta.com/camelcase",
              "path": "./schemas/test/camelcase"
            }
          }
        },
        "v2.0": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/v2.0"
        },
        "bundling": {
          "baseUri": "https://example.com/bundling",
          "path": "./schemas/test/bundling"
        },
        "doc": {
          "title": "A sample schema folder",
          "description": "For testing purposes",
          "github": "sourcemeta/one",
          "baseUri": "https://example.com/doc",
          "path": "./schemas/test/doc"
        },
        "hyper": {
          "baseUri": "https://example.com/hyper",
          "path": "./schemas/test/hyper"
        },
        "same": {
          "baseUri": "http://localhost:8000/same",
          "path": "./schemas/test/same"
        },
        "no-blaze": {
          "baseUri": "https://other.com",
          "path": "./schemas/test/no-blaze",
          "x-sourcemeta-one:evaluate": false
        },
        "no-base": {
          "path": "./schemas/test/no-base"
        }
      }
    }
  }
}

=== sourcemeta/one/test/e2e/headless/one.json
{
  "url": "http://localhost:8000",
  "html": false,
  "extends": [ "@self/v1" ],
  "contents": {
    "test": {
      "title": "Test",
      "description": "A directory full of testing schemas",
      "contents": {
        "extension": {
          "baseUri": "https://example.com/extension",
          "path": "./schemas/test/extension"
        },
        "schemas": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/folder",
          "defaultDialect": "http://json-schema.org/draft-07/schema#",
          "resolve": {
            "https://other.com/single.json": "/test/bundling/single.json"
          }
        },
        "v2.0": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/v2.0"
        },
        "bundling": {
          "baseUri": "https://example.com/bundling",
          "path": "./schemas/test/bundling"
        },
        "doc": {
          "title": "A sample schema folder",
          "description": "For testing purposes",
          "github": "sourcemeta/one",
          "baseUri": "https://example.com/doc",
          "path": "./schemas/test/doc"
        },
        "no-blaze": {
          "baseUri": "https://other.com",
          "path": "./schemas/test/no-blaze",
          "x-sourcemeta-one:evaluate": false
        },
        "no-base": {
          "path": "./schemas/test/no-base"
        }
      }
    }
  }
}

=== sourcemeta/one/enterprise/e2e/headless/one.json
{
  "url": "http://localhost:8000",
  "html": false,
  "extends": [ "@self/v1" ],
  "contents": {
    "test": {
      "baseUri": "https://example.com/schemas",
      "path": "./schemas/test",
      "x-sourcemeta-one:documentation": "./docs/test-readme.md"
    },
    "other": {
      "baseUri": "https://example.com/other",
      "path": "./schemas/other"
    }
  }
}
